### ISSUE TITLE
Mother 3 (1.3 Fan Translation) - Not working on ARMv5 platforms with <=64MB?

### ISSUE THREAD

**Issue by andymcca** [libretro/gpsp#190]
I'm trying to get this working on the Leapfrog Leapster Explorer and Didj platforms (ARM926EJS CPU (ARMv5te), 64MB and 32MB RAM respectively).  These console specs are very similar to the Miyoo/Bittboy/Pocketgo devices.

As of the latest lr-gpsp commit I either get a blank screen on ROM launch, or it restarts Retroarch.  I suspect this is ROM size-related as this is a 32MB ROM, but it goes in-game on gpsp 0.91 standalone.  

Looking back through the commits, I see the ROM buffering code was rewritten in commit  84cd7b2934146b7ad2917545f8d4c9fbbe97fea3 (July 14th 2021), so I would build from before this commit to test but ARMv5 support isn't added until a much later commit so the compilation fails.

Before I go too much further with this, can anyone with a Miyoo/Bittboy/Pocketgo or similar device running this SoC/RAM combination confirm whether it works for them?

Thanks!

**Comment by andymcca** [comment]
OK - to answer my own issue and in case anyone else has the same problem!!! -

A partial workaround for me is to build lr-gpsp using commit cc1a07462113e7018a2e898b8293bcc15057a5bf (May 13th 2021).

This is just before a commit which breaks ARM5TE compatibility, and is also before the July 13th 2021 commit which rewrites the ROM buffering code.  This produces a build which goes in-game on Leapster Explorer (64MB RAM) for as long as I tested it (wasn't all that long though).  It goes partially in-game on the Didj (32MB RAM), but crashes out just after the intro cut-scene (knocking on the door).

**Comment by andymcca** [comment]
Am now testing manually reducing translation cache (commit I'm using is before this was exposed as a compiler option), and manually reducing ROM buffer size in the old code before the rewrite.  

So far this seems to be working very well - reducing the buffer to 4MB appears to have no noticeable performance impact and increases available memory on the platform by around 10MB.  Am waiting to hear regarding testing on a 32MB platform as I don't have one personally.

**Comment by Apaczer** [comment]
@andymcca FYI the "_Yu-Gi-Oh! - Ultimate Masters 2006_" which is more than 32MB, loads&plays fine on official MIYOO arm32 console with libretro/gpsp (which I can't tell about our [standalone](https://github.com/Apaczer/gpsp) builds, where sound is broken).

**Comment by Apaczer** [comment]
RAM == 32MB (as on all Miyoo 1st gen consoles with F1C100S soc)

Libretro/gpsp == latest nigthly

Do u want me to try other games nevertheless?

**Comment by andymcca** [comment]
Yes please @Apaczer , that would be great.  Please try Pokemon FireRed Gaia and Mother 3 1.3 translation.

The symptoms I and others get when starting these ROMS are a black screen for a few seconds and then a Retroarch crash which takes me back to Gmenunx (frontend).  Retroarch logs don't have any errors in them prior to the crash.  This only appears to happen on 32MB ROMS.

Explorer/Didj SoC is remarkably similar to the F1C100S spec - same processor, same RAM.

If you successfully try these then it may be that the problem lies elsewhere.

**Comment by Apaczer** [comment]
The "Mother 3" with or without translation works with no issue (same
setup). I won't go any futher as I do not have access to FireRed Gaia.

**Comment by andymcca** [comment]
Thank you Apaczer - I will go back to the drawing board on this one.

**Comment by davidgfnet** [comment]
I will take a look at this when i get some time, shouldnt be hard to fix I think.

**Comment by andymcca** [comment]
Thanks @davidgfnet, although @Apaczer seems to confirm it's not a problem on the Miyoo platform which is essentially the same spec.  So I'm not entirely sure what the issue is.

**Comment by davidgfnet** [comment]
I just added some fixes that should fix this issue. Performance is not great with low-memory devices and big ROMs, so I will try to come up with a better solution for Linux-based platforms (where we can use the MMU to our favour).
Can you please verify that this is no longer an issue? Thanks!

**Comment by andymcca** [comment]
Hi David,

Thanks - i built from this commit this morning but the issue remains the
same on the Explorer at 32MB at least, probably needing a mmap solution as
you suggested.

It is even worse if I specify a low ROM Buffer (4MB) on compilation, as
then nothing works (not even a smaller ROM like Double Dragon).

Strange as this option is set for the RS90 which also has 32MB RAM, albeit
MIPS based.

Will await your further commits before retrying.

Many Thanks for your help!
Andy

**Comment by davidgfnet** [comment]
Does it crash then? Also, how do you build it for the 32MB explorer device? Thanks!

**Comment by andymcca** [comment]
Yes it now crashes due to running out of memory - I've tried again this morning and this time also studied the device logs.  

On the version before your recent commits it would just stay on a black screen.  Following the recent commits, according to the logs Linux detects the out of memory condition and kills the Retroarch process, which then returns me back to gmenunx on the device (reload).

4MB and 8MB ROMS on your latest commit work ok.  Anything higher crashes.  Building with a specific earlier commit and ALSO manually reducing the ROM Buffer in the code to 4MB (the ROM_BUFFER_SIZE compile value isn't implemented at the time of this commit) produces a working build as referenced here - https://github.com/libretro/gpsp/issues/190#issuecomment-1435786105.  

Otherwise the default behaviour of the earlier build is to allocate as much RAM as possible in 2MB chunks which takes the Explorer 32MB very close to its limit, hence an eventual crash.  It seems that even specifying a low ROM_BUFFER_SIZE on compilation (e.g. 4MB) on your recent commit doesn't seem to prevent the out of memory condition.

I cross-compile it for the Explorer using the Buildroot/Toolchain from Retroleap (https://github.com/mac2612/retroleap).  I specify Miyoo as the target since this shares the same CPU (armv5te) as the Explorer, but obviously use the Retroleap toolchain.

**Comment by andymcca** [comment]
An update on this.

I have rebuilt my core using the latest commit 2bbd770, removed the SMALL_TRANSLATION_CACHE flag and manually specified a smaller ROM_BUFFER_SIZE in gpsp_config.h (I set it to 4 instead of 32).

This has resulted in a working build which loads all ROMS ok regardless of size.  I don't know what was happening above but all now appears to be working ok!  So I will close this issue.

**Comment by DrUm78** [comment]
Hardware: FunKey S device (armv7 32-bit) with 64MB RAM
Software: PicoArch
OS: Custom Linux 4.14.14

@davidgfnet @andymcca Mother 3 JAP or with FR patch 1.9 still crash for me at launch on classic_armv7_a7 (with and without dynarec) then it makes all games impossible to launch as the RAM is not emptied. Therefore I need to restart the device.

**Comment by DrUm78** [comment]
@andymcca Could we reopen this ticket so I do not create another one?

**Comment by andymcca** [comment]
@DruM78 ok I've reopened the issue - I'm will test this a little more on my device again, it still seems if I build from commits earlier than 2bbd77054ee8af4bc9d81af22a7cd72301f90fcb then I get a similar issue but I'm not sure if/how it's related yet.  Are you loading the ROM uncompressed (i.e. no zip file)?  I haven't tried that combination of Mother 3 JP and FR patch 1.9, so will try on my own device to see if it gives a problem.

**Comment by DrUm78** [comment]
@andymcca Damn the issue only occurs with the zipped file, it works fine unzipped. 🤔
All other my games work fine zipped though. I tried unzipping it then zipping it again but in vain, still the same crash.

**Comment by DrUm78** [comment]
@andymcca Yeah the FunKey needs a bit for the Linux OS (about 19% of 64MB of RAM) so yeah it won't have 64MB of RAM available to unzip the archive.
But my point here was that the required amount of RAM seemed significantly higher than with 1.43 direct port: it actually takes 76% of my 64MB RAM (OS + zipped ROM) with the direct port, so that's why I thought something was wrong here.
But in any case, playing Mother 3 unzipped is an option. 👍

**Comment by andymcca** [comment]
By direct port, do you mean gpsp standalone (or gpsp rumble)?  Those versions use zlib to work with the compressed files.  The libretro fork uses RetroArch built-in function for unzipping files, which currently takes a lot more RAM to perform the unzip.

I'll close this again now though given the issue isn't Mother 3-specific.

**Comment by davidgfnet** [comment]
Hey, sorry I missed this issue.
Around that time I added this PR to retroarch. https://github.com/libretro/RetroArch/pull/15220
This allows ZIP extractions without using a ton of memory (just uses a small buffer instead). Can you check whether this helps at all?

**Comment by DrUm78** [comment]
Nope, it does not work with zipped Mother 3 and 64 MB of RAM, even with the latest code but I think it's because of the frontend I use (PicoArch). It works with SDLRetro (another light frontend) though.

**Comment by davidgfnet** [comment]
I hit you on Discord btw, if you feel it's faster.
We had some issues with rom hacks, I hope it's not that. So you are using picoarch as a frontend and the latest gpsp right?

**Comment by DrUm78** [comment]
I accepted your friend request. Yes I use the latest code (188887e6c8a5e5d6b3282e2b07804d0cf3db5314).
According to PicoArch's author, that's because the zipped ROM is extracted to tmp file, /tmp is only 28MB on the FunKey S device, so even 32MB + 128KB is too much here so nothing you can fix on your side. Maybe I will tweak /tmp size in my custom OS then.

**Comment by DrUm78** [comment]
Confirmed to work with `/tmp` >= 33MB, thanks for your help! 👍

**Comment by davidgfnet** [comment]
Gotcha! Yeah extracting to a temporary directory can do that. So it's an issue with the frontend.
I plan to add support in gpsp for zip file (ie. the frontend extracts the ROM to memory and is used from there). Stay tuned
